[package]
name = "stubborn-io"
version = "0.3.1"
authors = ["David Raifaizen <david.raifaizen@protonmail.com>"]
edition = "2018"
description = "io traits/structs that automatically recover from potential disconnections/interruptions."
license = "MIT"
keywords = ["reconnect", "retry", "stubborn", "io", "StubbornTcpStream"]
repository = "https://github.com/craftytrickster/stubborn-io"
documentation = "https://docs.rs/stubborn-io"
readme = "README.md"

[features]
default = ["tokio"]

[dependencies]
tokio = { version = "1", features = ["time"], optional = true }
async-std = { version = "1", optional = true }
log = "0.4"
futures = "0.3"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "fs", "io-util"] }
futures = "0.3"
