[package]
name = "stubborn-io"
version = "0.1.1"
authors = ["David Raifaizen <d-raif@outlook.com>"]
edition = "2018"
description = "io traits/structs that automatically recover from potential disconnections/interruptions."
license = "MIT"
keywords = ["reconnect", "persistent", "stubborn", "io"]
 
[dependencies]
tokio = { git = "https://github.com/tokio-rs/tokio", features = ["rt-full"] }
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
bytes = "0.4"
mio = "0.6"
log = "0.4"