[package]
name = "stubborn-stream" # stubborn-io
version = "0.1.0"
authors = ["David Raifaizen <d-raif@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { git = "https://github.com/tokio-rs/tokio", features = ["rt-full"] }
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
bytes = "0.4"
mio = "0.6"