[package]
name = "stubborn-io"
version = "0.1.2"
authors = ["David Raifaizen <d-raif@outlook.com>"]
edition = "2018"
description = "io traits/structs that automatically recover from potential disconnections/interruptions."
license = "MIT"
keywords = ["reconnect", "retry", "stubborn", "io", "StubbornTcpStream"]
repository = "https://github.com/craftytrickster/stubborn-io"
readme = "README.md"
 
[dependencies]
tokio = "=0.2.0-alpha.1"
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
bytes = "0.4"
mio = "0.6"
log = "0.4"
